import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Slider from "../components/Slider";
import Words from "../components/Words";
import ProductCard from "../components/ProductCard";
import Location from "../components/Location";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Plantarium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Slider />
      <Words />
      <div style={{ display: "flex" }}>
        <ProductCard />
        <ProductCard />
        <ProductCard />
        <ProductCard />
      </div>

      <Location />
    </div>
  );
}
