import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Slider from "../components/Slider";
import Words from "../components/Words";
import ProductCard from "../components/ProductCard";
import Location from "../components/Location";
import axios from "axios";

export default function Home({ products }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Plantarium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Slider />
      <Words />
      <div style={{ display: "flex" }}>
        {products.map((product) => {
          <ProductCard products={product} />;
        })}
      </div>
      <Location />
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get("http://localhost:3000/api/product");
  const products = res.data;

  return {
    props: { products },
  };
};
